server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: SM-SERVICE
          uri: lb://SM-SERVICE
          predicates:
            - Path=/supermarket/**
